[target.xtensa-esp32-none-elf]
# runner = "probe-rs run --chip=esp32 --preverify --always-print-stacktrace --no-location --catch-hardfault"
runner = "espflash flash --monitor"

[env]

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-Z", "stack-protector=all",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
